### ISSUE TITLE
writing pre-encoded h264 frame to mp4

### ISSUE THREAD

**Issue by hagaygo** [TalAloni/MP4Maker#1]
Hi Tal,

I am trying to create a mp4 file from RTSP stream. (https://github.com/BogdanovKirill/RtspClientSharp/issues/68)

Did quick & dirty test with your code here , no success yet. (wrote the raw RTSP H264 frames to a file and then tried to mux it to mp4)

> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaFormatLibrary.H264.SliceHeader..ctor(RawBitStream bitStream, SequenceParameterSetList spsList, PictureParameterSetList ppsList, Boolean idrPicFlag, Byte nalRefIdc)
   at MediaFormatLibrary.H264.CodedSlice.ReadDecodedPayloadBytes(RawBitStream bitStream)
   at MediaFormatLibrary.H264.CodedSlice..ctor(MemoryStream stream, SequenceParameterSetList spsList, PictureParameterSetList ppsList)
   at MediaFormatLibrary.H264.NalUnitHelper.GetNalUnit(MemoryStream stream, SequenceParameterSetList spsList, PictureParameterSetList ppsList)
   at MediaFormatLibrary.H264.H264ElementaryStreamReader.ReadAccessUnitNALs()
   at MediaFormatLibrary.H264.H264ElementaryStreamReader.ReadDecodedAccessUnit()
   at MediaFormatLibrary.H264MultiplexerInput.ReadParameterSets()
   at MediaFormatLibrary.H264MultiplexerInput.GetMP4SampleEntry()
   at MP4Maker.Program.OpenTracks(List`1 inputList)
   at MP4Maker.Program.MuxMP4(List`1 inputList, String outputPath, MultiplexerProfile multiplexerProfile, Boolean enableCTTSv1)
   at MP4Maker.Program.Main(String[] args)

Is it possible at all with the current code ?

Thanks (Again) for your great work.

**Comment by TalAloni** [comment]
If memory serves me right, there's a slight different between how the H264 NAL units are stored in a multiplexed stream vs. in raw form (there's a size prefix IIRC), so when you "demux" from RTSP you should "convert" to the raw form.
You should inspect how other de-multiplexers do it. once you have a proper raw .H264, it shouldn't be a problem to mux it into MP4.

**Comment by TalAloni** [comment]
Note that the first H264 frame must be an I frame of course.
